"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/input";
import { toast } from "@/components/ui/sonner";
import { startEnrol, verifyTotp, type EnrolData } from "./actions";

/** `factorId` set → verify mode; otherwise enrol mode (QR first). */
export function MfaForm({ factorId }: { factorId: string | null }) {
  const router = useRouter();
  const [enrol, setEnrol] = useState<EnrolData | null>(null);
  const [code, setCode] = useState("");
  const [pending, start] = useTransition();
  const activeFactor = factorId ?? enrol?.factorId ?? null;

  const begin = () =>
    start(async () => {
      const res = await startEnrol();
      if (res.ok && res.data) setEnrol(res.data);
      else if (!res.ok) toast.error(res.error);
    });

  const verify = () =>
    start(async () => {
      if (!activeFactor) return;
      const res = await verifyTotp({ factorId: activeFactor, code });
      if (res.ok) {
        router.replace("/admin/overview");
        router.refresh();
      } else toast.error(res.error);
    });

  if (!factorId && !enrol) {
    return (
      <div className="flex flex-col gap-3">
        <p className="text-sm text-text-muted">
          Tài khoản quản trị bắt buộc dùng ứng dụng xác thực (Google Authenticator, Authy...). Thiết lập lần đầu:
        </p>
        <Button onClick={begin} disabled={pending}>Thiết lập ứng dụng xác thực</Button>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-3">
      {enrol && (
        <>
          <p className="text-sm text-text-muted">Quét mã QR bằng ứng dụng xác thực, rồi nhập mã 6 số.</p>
          {/* qr_code is a data: URI SVG generated by Supabase Auth */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={enrol.qr} alt="Mã QR thiết lập xác thực hai bước" width={192} height={192} className="mx-auto" />
          <p className="break-all text-center text-xs text-text-muted">Hoặc nhập khóa: {enrol.secret}</p>
        </>
      )}
      <Label htmlFor="totp">Mã xác thực 6 số</Label>
      <Input
        id="totp" inputMode="numeric" autoComplete="one-time-code" maxLength={6}
        value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
      />
      <Button onClick={verify} disabled={pending || code.length !== 6}>
        {pending ? "Đang xác thực..." : "Xác nhận"}
      </Button>
    </div>
  );
}
